config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :categories
  resources :expenses

  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :expences
  belongs_to :user
  before_save :title_capitalize

  validates :title, presence: true
  validates_uniqueness_of :title, scope: :user_id

  paginates_per 100

  def title_capitalize
    self.title = Unicode::capitalize(title.strip)
  end


end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  before_save :title_capitalize

  validates :title, :price, :category_id, presence: true

  paginates_per 100

  def title_capitalize
    self.title = Unicode::capitalize(title.strip)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :categories
  has_many :expenses

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = current_user.categories.page(params[:page])
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = current_user.categories.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:edit, :new, :create, :update]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = current_user.expenses.includes(:category).order(created_at: :desc).page(params[:page])
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = current_user.expenses.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = current_user.expenses.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = current_user.expenses.find(params[:id])
    end

    def set_categories
      @categories = current_user.categories.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:title, :description, :price, :purchase_date, :category_id)
    end
end

app/controllers/home_controller.rb
require 'date'

class HomeController < ApplicationController
  def index
    date = Time.now

    @categories = current_user.categories
    @from = date.beginning_of_year
    @to = date.end_of_year

    if params[:scope].present?
      case params[:scope]
      when 'day'
        @from = date.beginning_of_day
        @to = date.end_of_day
      when 'month'
        @from = date.beginning_of_month
        @to = date.end_of_month
      when 'year'
        @from = date.beginning_of_year
        @to = date.end_of_year
      end
    end

    if params[:from].present?
      begin
        @from = DateTime.parse(params[:from])
      rescue
      end
    end

    if params[:to].present?
      begin
        @to = DateTime.parse(params[:to])
      rescue
      end

    end

    sum_lambda = ->(k, v) { { label: k, y: v.sum {|e| e.price.to_f}} }

    expenses = current_user.expenses.includes(:category).where(:purchase_date => @from..@to)
    expenses = expenses.where(category: params[:categories]) if params[:categories].present?

    @by_month = expenses.group_by {|i| i.purchase_date.strftime("%B") }.map(&sum_lambda)
    @by_categories = expenses.group_by {|i| i.category.title }.map(&sum_lambda)
    @by_title = expenses.group_by { |i| i.title }.map(&sum_lambda)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def chart_dates(from, to)
    res = ''
    res << " с #{from} " if from.present?
    res << " до #{to} " if to.present?

    res
  end

  def check_category_status(params, item_id)
    res = false

    if params['categories'].present?
      res = params['categories'].include?(item_id.to_s)
    end

    res
  end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<%= link_to 'New Category', new_category_path %>

<br>

<div class="table-blue">
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.title %></td>
          <td><%= category.description %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Category', new_category_path %>

<br>

<%= paginate @categories %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :purchase_date %><br>
    <%= f.text_field :purchase_date, value: f.object.purchase_date || DateTime.now %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select(:category_id, @categories, :id, :title) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Expenses</h1>

<%= link_to 'New Expense', new_expense_path %>

<br>

<div class="table-blue">
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Категория</th>
        <th>Price</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @expenses.each do |expense| %>
        <tr>
          <td><%= expense.title %></td>
          <td><%= expense.description %></td>
          <td><%= expense.category.title %></td>
          <td><%= expense.price %></td>
          <td><%= expense.purchase_date %></td>
          <td><%= link_to 'Show', expense %></td>
          <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
          <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Expense', new_expense_path %>

<br>

<%= paginate @expenses %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @expense.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @expense.purchase_date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @expense.price %>
</p>

<p>
  <strong>Категория:</strong>
  <%= @expense.category.title %>
</p>


<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/home/index.html.erb
<div class="columnsContainer">
  <div class="leftColumn">
    <ul>
      <li>
        <%= link_to 'За день', params.merge({ scope: 'day'}) %>
      </li>
      <li>
        <%= link_to 'За месяц', params.merge({ scope: 'month'}) %>
      </li>
      <li>
        <%= link_to 'За год', params.merge({ scope: 'year'}) %>
      </li>
    </ul>

    <form action="<%= root_path %>" >
      <ul>
        <% @categories.each do |category| %>
          <li>
            <%= category.title %>
            <%= check_box_tag('categories[]', category.id, check_category_status(params, category.id)) %>
          </li>
        <% end %>
        <li><button>Отправить</button></li>
        <ul>
        </form>

      </div>

      <div class="rightColumn">

        <div id="chartContainer-monthly" style="height: 400px; width: 100%;"></div>
        <div id="chartContainer-categoryes" style="height: 400px; width: 100%;"></div>
        <div id="chartContainer-title" style="height: 400px; width: 100%;"></div>

        <script type="text/javascript">

        var chart = new CanvasJS.Chart("chartContainer-monthly", {
          title:{
            text: "Помесячный отчет <%= chart_dates(@from, @to)%>"
          },
          data: [
            {
              // Change type to "doughnut", "line", "splineArea", etc.
              type: "column",
              indexLabel: "{y}",
              dataPoints: <%= @by_month.to_json.html_safe %>
            //   [
              //   { label: "apple",  y: 10  },
              //   { label: "orange", y: 15  },
              //   { label: "banana", y: 25  },
              //   { label: "mango",  y: 30  },
              //   { label: "grape",  y: 28  }
              // ]
            }
          ]
        });
        chart.render();

        var chart2 = new CanvasJS.Chart("chartContainer-categoryes", {
          title:{
            text: "По категориям <%= chart_dates(@from, @to)%>"
          },
          data: [
            {
              // Change type to "doughnut", "line", "splineArea", etc.
              type: "column",
              indexLabel: "{y}",
              dataPoints: <%= @by_categories.to_json.html_safe %>
            }
          ]
        });
        chart2.render();

        var chart3 = new CanvasJS.Chart("chartContainer-title", {
          title:{
            text: "По найменованиям <%= chart_dates(@from, @to)%>"
          },
          data: [
            {
              // Change type to "doughnut", "line", "splineArea", etc.
              type: "column",
              indexLabel: "{y}",
              dataPoints: <%= @by_title.to_json.html_safe %>
            }
          ]
        });
        chart3.render();


        </script>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EApp</title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <ul class="top-menu">
      <li><%= active_link_to 'Главная', root_path, :active => :exclusive %></li>
      <li><%= active_link_to 'Расходы', expenses_path %></li>
      <li><%= active_link_to 'Категории', categories_path %></li>
      <ul class="top-menu-right">
        <li><%= active_link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
      </ul>
    </ul>
  <% end %>

  <% if notice.present? %>
    <p class="notice"><%= notice %></p>
  <% end %>

  <% if alert.present? %>
    <p class="alert"><%= alert %></p>
  <% end %>


  <%= yield %>

</body>
</html>